version: '3.8'
services:
  oracle-db:
    image: gvenzl/oracle-free:23-slim-faststart
    container_name: oracle-campus
    environment:
      ORACLE_PASSWORD: campus
      APP_USER: campus
      APP_USER_PASSWORD: campus
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    restart: unless-stopped

volumes:
  oracle_data: